const envConfig = {
  TWITTER_API_KEY: process.env.NEXT_PUBLIC_TWITTER_API_KEY || "",
  TWITTER_API_SECRET: process.env.NEXT_PUBLIC_TWITTER_API_KEY_SECRET || "",
  TWITTER_BEARER_TOKEN: process.env.NEXT_PUBLIC_TWITTER_BEARER_TOKEN || "",
  TWITTER_CLIENT_ID: process.env.NEXT_PUBLIC_TWITTER_CLIENT_ID || "",
  TWITTER_CLIENT_SECRET: process.env.NEXT_PUBLIC_TWITTER_CLIENT_SECRET || "",
  BASE_DOMAIN: process.env.NEXT_PUBLIC_BASE_DOMAIN || "",
};

export default envConfig;
